"""Camoufox + Firefox implementation of the BrowserModule interface.

Camoufox is a hardened Firefox fork that spoofs fingerprints at the C++
implementation layer (not via JS injection), making spoofed attributes
appear native.  This avoids the main failure mode of patched Chromium
implementations where fingerprint vectors are detectable as JavaScript
property overrides.

Capture subsystem differences vs PlaywrightChromiumModule:
- CDPResponseTap is dropped: CDP is Chromium-only; Firefox exposes no
  equivalent new_cdp_session() surface.  HAR attach mode covers response
  bodies.
- RouteDocumentInterceptor is dropped: context.route() triggers
  PerimeterX/Datadome detections and defeats camoufox's stealth purpose.
  Firefox does not have Chromium's main-frame body disposal race, so the
  route interceptor's primary motivation doesn't apply.
- stealth.js is not injected: camoufox patches fingerprint vectors at the
  C++ level via BrowserForge; a JS init script would add an extra layer
  that could itself be flagged as an inconsistency.

NetworkCapture and WebSocketCapture (event listeners, not route handlers)
are safe and fully compatible with camoufox's Playwright-based API.
"""

from __future__ import annotations

import asyncio
import json
import logging
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from agent.browser.base import BrowserModule, DetonationRequest, DetonationResult, StealthProfile
from agent.browser.network_capture import NetworkCapture
from agent.browser.websocket_capture import WebSocketCapture

logger = logging.getLogger(__name__)


class CamoufoxFirefoxModule(BrowserModule):
    """Browser automation via Camoufox driving a hardened Firefox build.

    Uses camoufox's persistent_context mode so the profile looks like a
    real user session.  Fingerprints are generated by BrowserForge and
    injected at the C++ level — no JS init script patching required.
    """

    def __init__(self) -> None:
        self._camoufox: Any = None
        self._context: Any = None
        self._page: Any = None
        self._artifact_dir: Path | None = None
        self._console_messages: list[dict] = []
        self._navigations: list[dict] = []
        self._paused: asyncio.Event = asyncio.Event()
        self._paused.set()  # not paused initially
        self._stealth_enabled: bool = True
        self._screenshot_tasks: list[asyncio.Task] = []

    @property
    def name(self) -> str:
        return "camoufox_firefox"

    async def launch(self, artifact_dir: Path) -> None:
        """Prepare artifact directory.  The browser launches in detonate()."""
        self._artifact_dir = artifact_dir
        self._artifact_dir.mkdir(parents=True, exist_ok=True)
        logger.info("CamoufoxFirefoxModule ready (browser launches at detonate time)")

    async def detonate(self, request: DetonationRequest) -> DetonationResult:
        assert self._artifact_dir is not None, "call launch() first"

        from camoufox.async_api import AsyncCamoufox
        from browserforge.fingerprints import FingerprintGenerator, Screen

        har_path = self._artifact_dir / "har_full.har"
        self._console_messages = []
        self._navigations = []

        stealth = request.stealth if request.stealth is not None else StealthProfile()
        self._stealth_enabled = stealth.enabled

        user_data_dir = str(self._artifact_dir / "user-data")

        # Generate a BrowserForge fingerprint that is internally consistent
        # with the running Firefox version.  BrowserForge models the real-world
        # statistical distribution of device attributes, so the spoofed set
        # matches a plausible real user rather than a uniform random sample.
        if stealth.enabled:
            fg = FingerprintGenerator(browser="firefox", os="windows")
            fingerprint = fg.generate(
                screen=Screen(
                    max_width=stealth.viewport_width,
                    max_height=stealth.viewport_height,
                )
            )
            camoufox_kwargs: dict[str, Any] = dict(
                os="windows",
                headless=False,
                persistent_context=True,
                user_data_dir=user_data_dir,
                fingerprint=fingerprint,
                locale=stealth.locale,
                geoip=False,  # set geolocation below via context API
                record_har_path=str(har_path),
                record_har_content="attach",
                ignore_https_errors=True,
            )
            if stealth.user_agent:
                camoufox_kwargs["user_agent"] = stealth.user_agent
        else:
            camoufox_kwargs = dict(
                headless=False,
                persistent_context=True,
                user_data_dir=user_data_dir,
                record_har_path=str(har_path),
                record_har_content="attach",
                ignore_https_errors=True,
            )

        # Use __aenter__/__aexit__ explicitly so close() can tear down the
        # browser if the run is interrupted before detonate() returns.
        self._camoufox = AsyncCamoufox(**camoufox_kwargs)
        self._context = await self._camoufox.__aenter__()

        try:
            if stealth.enabled:
                # Geolocation must be set via context API since camoufox's
                # geoip auto-detection is disabled above.
                await self._context.grant_permissions(["geolocation"])
                await self._context.set_geolocation({
                    "latitude": stealth.geolocation_lat,
                    "longitude": stealth.geolocation_lon,
                })

            capture = NetworkCapture(self._artifact_dir / "bodies")
            capture.attach(self._context)
            ws_capture = WebSocketCapture(self._artifact_dir / "bodies")

            self._page = await self._context.new_page()

            await ws_capture.attach_to_context(self._context)
            self._page.on("console", self._on_console)
            self._page.on("pageerror", self._on_page_error)

            def _on_framenavigated(frame: Any) -> None:
                self._navigations.append({
                    "timestamp": datetime.now(UTC).isoformat(),
                    "url": frame.url,
                    "frame": "main" if frame == self._page.main_frame else "sub",
                })

            self._page.on("framenavigated", _on_framenavigated)

            screenshot_paths: list[Path] = []
            self._screenshot_tasks = []

            def _on_load(_: Any) -> None:
                if self._page and self._artifact_dir:
                    path = self._artifact_dir / f"screenshot_{int(time.time() * 1000)}.png"

                    async def _capture() -> None:
                        try:
                            await self._page.screenshot(path=str(path), full_page=True)
                            screenshot_paths.append(path)
                        except Exception:
                            logger.debug("Load-event screenshot failed (page may be navigating)")

                    self._screenshot_tasks.append(asyncio.create_task(_capture()))

            self._page.on("load", _on_load)

            try:
                logger.info("Navigating to %s", request.url)
                await self._page.goto(
                    request.url,
                    timeout=request.timeout_sec * 1000,
                    wait_until="domcontentloaded",
                )

                if request.wait_for_idle:
                    try:
                        await self._page.wait_for_load_state(
                            "networkidle", timeout=request.timeout_sec * 1000
                        )
                    except Exception:
                        logger.warning("Network idle timeout — proceeding with capture")

                try:
                    fp = await self._page.evaluate("""() => ({
                        webdriver: navigator.webdriver,
                        languages: [...navigator.languages],
                        hardware_concurrency: navigator.hardwareConcurrency,
                        max_touch_points: navigator.maxTouchPoints,
                        platform: navigator.platform,
                        product: navigator.product,
                        vendor: navigator.vendor,
                    })""")
                    logger.debug("Browser fingerprint: %s", fp)
                except Exception as fp_exc:
                    logger.debug("Browser fingerprint eval failed: %s", fp_exc)

                if request.interactive:
                    logger.info("Interactive mode — pausing for analyst takeover")
                    self._paused.clear()
                    await self._paused.wait()
                    logger.info("Interactive mode — resumed")

            except Exception as exc:
                logger.error("Navigation error: %s", exc)
                await ws_capture.drain()
                await capture.drain()
                stats = capture.finalize()
                return DetonationResult(error=str(exc), meta=self._build_meta(stats))

            await asyncio.gather(*self._screenshot_tasks, return_exceptions=True)
            self._screenshot_tasks = []

            dom_path = self._artifact_dir / "dom.html"
            dom_content = await self._page.evaluate("document.documentElement.outerHTML")
            dom_path.write_text(dom_content, encoding="utf-8")

            navigations_path = self._artifact_dir / "navigations.json"
            navigations_path.write_text(
                json.dumps(self._navigations, indent=2), encoding="utf-8"
            )

            console_path = self._artifact_dir / "console.json"
            console_path.write_text(
                json.dumps(self._console_messages, indent=2), encoding="utf-8"
            )

            await ws_capture.drain()
            await capture.drain()
            stats = capture.finalize()

            ws_data = ws_capture.finalize()
            if ws_data:
                ws_path = self._artifact_dir / "websockets.json"
                ws_path.write_text(json.dumps(ws_data, indent=2, default=str), encoding="utf-8")

            await self._context.close()
            self._context = None
            self._page = None

            return DetonationResult(
                har_path=har_path,
                screenshot_paths=screenshot_paths,
                dom_path=dom_path,
                navigations_path=navigations_path,
                console_log_path=console_path,
                meta=self._build_meta(stats),
            )

        finally:
            if self._camoufox is not None:
                try:
                    await self._camoufox.__aexit__(None, None, None)
                except Exception:
                    pass
                self._camoufox = None
                self._context = None
                self._page = None

    @property
    def is_paused(self) -> bool:
        return not self._paused.is_set()

    async def pause(self) -> None:
        self._paused.clear()

    async def resume(self) -> None:
        self._paused.set()

    async def close(self) -> None:
        if self._camoufox is not None:
            try:
                await self._camoufox.__aexit__(None, None, None)
            except Exception:
                pass
            self._camoufox = None
            self._context = None
            self._page = None
        logger.info("Camoufox Firefox closed")

    def _on_console(self, msg: Any) -> None:
        self._console_messages.append({
            "type": msg.type,
            "text": msg.text,
            "timestamp": time.time(),
        })

    def _on_page_error(self, error: Any) -> None:
        self._console_messages.append({
            "type": "error",
            "text": str(error),
            "timestamp": time.time(),
        })

    def _build_meta(self, stats: NetworkCapture | None = None) -> dict[str, Any]:
        from agent.browser.network_capture import CaptureStats
        meta: dict[str, Any] = {
            "browser_module": self.name,
            "browser": "firefox",
            "stealth_enabled": self._stealth_enabled,
            "browser_driver": "camoufox",
        }
        if isinstance(stats, CaptureStats):
            meta["capture_stats"] = stats.as_dict()
        return meta
